### ISSUE TITLE
inventory slots 

### ISSUE THREAD

**Issue by imjimmyha** [the-isf-academy/quest#31]
You can limit the number of things you have in your inventory. FOr example, you need to collect apples, but if you put a limit on the number of apples you can carry, it =would make the game more difficult. 

As I have said, in the game, you have to interact with things one way of interacting is picking up and dropping objects, you can use the inventory system to strategize what you carry. 
A clear and concise description of how this feature may be used in games made with the Quest framework.

**Additional context**
Anything else?

**Comment by WalkerChak** [comment]
I was thinking depending on the game, the user can choose how many they want, 1 to 24 slots. it all depends on how many items will exist in your game.

**Comment by wolfj95** [comment]
moving to #29
