### ISSUE TITLE
Spelling/Grammar Mistakes

### ISSUE THREAD

**Issue by ProvokingQuestions** [the-isf-academy/quest#47]
In 'Sprite Directionality', there is a parameter called 'player_sprite_image_lr (string)'. The description is 'file path to image for left and righ player sprite image', and the 'right' is missing a t.

In 'Timer', the description of what the code does says 'Maintains a clock for the game that can enforced time-based game states and elements like a countdown.'. It says 'enforced' in past tense when I'm pretty sure it should be 'enforce' in present tense.

In 'Maze Walk Strategy', the description states 'We just need to choose new targets i a way that gets the sprite around the maze.'. I believe it should be 'in a way', not 'i a way'.

That's all, it's not related to code, sorry if this wastes a ton of time.

**Comment by wolfj95** [comment]
Thanks for pointing out these typos @ProvokingQuestions ! You're helping improve the questgame library a ton. I fixed them in commit f8c5aa2.

Also, if you want to fix issues like these in the future, you can create a branch off the master branch like `git checkout -b typos` and fix the typos yourself. Once you commit your code, you can create a pull request like we did in the feature lab and then we'll merge it in to update the master branch of this library.

Thanks again!
